insert into USUARIO (EMAIL, SENHA, PERMISSAO_ADMINISTRADOR, PERMISSAO_FUNCIONARIO, PERMISSAO_CIDADAO)
values('admin','admin', true, false, false);

insert into COMORBIDADE values (1, 'DIABETES');
insert into COMORBIDADE values (2, 'PRESSAO_ALTA');
insert into COMORBIDADE values (3, 'ASMA');

-- Vacinas

-- INSERT INTO vacina (ID, NOME_FABRICANTE, TELEFONE_FABRICANTE, NUMERO_DOSES, TEMPO_ENTRE_DOSES)
-- VALUES (1000, 'nomeFabricante1', '12345678910', 1, 0);
--
-- INSERT INTO vacina (ID, NOME_FABRICANTE, TELEFONE_FABRICANTE, NUMERO_DOSES, TEMPO_ENTRE_DOSES)
-- VALUES (1001, 'nomeFabricante2', '12345678911', 2, 1);

-- -- Lotes

-- INSERT INTO lote (ID, DATA_DE_VALIDADE, RESERVADAS_PRIMEIRA_DOSE, RESERVADAS_SEGUNDA_DOSE, VACINA_ID)
-- VALUES (2000, '2021-06-14T21:17:19.437Z', 2, 0, 1000);
--
-- INSERT INTO lote (ID, DATA_DE_VALIDADE, RESERVADAS_PRIMEIRA_DOSE, RESERVADAS_SEGUNDA_DOSE, VACINA_ID)
-- VALUES (2001, '2021-06-14T21:17:19.437Z', 1, 1, 1001);

-- Estados Vacinacao

-- INSERT INTO vacinacao_state (ID, DTYPE)
-- VALUES (10001, 'NaoHabilitadoState');

-- INSERT INTO vacinacao_state (ID, DTYPE)
-- VALUES (2, 'HabilitadoPrimeiraDoseState');
--
-- INSERT INTO vacinacao_state (ID, DTYPE)
-- VALUES (3, 'EsperandoSegundaDoseState');
--
-- INSERT INTO vacinacao_state (ID, DTYPE)
-- VALUES (4, 'HabilitadoSegundaDoseState');
--
-- INSERT INTO vacinacao_state (ID, DTYPE)
-- VALUES (5, 'VacinacaoFinalizadaState');

-- Registros

-- INSERT INTO registro_vacinacao (NUMERO_CARTAO_SUS, DATA_AGENDAMENTO, DATA_VACINACAO_PRIMEIRA_DOSE, DATA_VACINACAO_SEGUNDA_DOSE, ESTADO_VACINACAO_ID, VACINA_ID)
-- VALUES ('numeroCartaoSus1', null, '1950-05-14', null, 3, 1001);
--
-- INSERT INTO registro_vacinacao (NUMERO_CARTAO_SUS, DATA_AGENDAMENTO, DATA_VACINACAO_PRIMEIRA_DOSE, DATA_VACINACAO_SEGUNDA_DOSE, ESTADO_VACINACAO_ID, VACINA_ID)
-- VALUES ('numeroCartaoSus2', null, null, null, 10001, null);
--
-- INSERT INTO registro_vacinacao (NUMERO_CARTAO_SUS, DATA_AGENDAMENTO, DATA_VACINACAO_PRIMEIRA_DOSE, DATA_VACINACAO_SEGUNDA_DOSE, ESTADO_VACINACAO_ID, VACINA_ID)
-- VALUES ('numeroCartaoSus3', null, null, null, 10001, null);
--
-- INSERT INTO registro_vacinacao (NUMERO_CARTAO_SUS, DATA_AGENDAMENTO, DATA_VACINACAO_PRIMEIRA_DOSE, DATA_VACINACAO_SEGUNDA_DOSE, ESTADO_VACINACAO_ID, VACINA_ID)
-- VALUES ('numeroCartaoSus4', null, null, null, 10001, null);
--
-- -- Cidadaos
--
-- INSERT INTO cidadao (CPF, DATA_NASCIMENTO, ENDERECO, NOME, PROFISSAO, TELEFONE, REGISTRO_VACINACAO_NUMERO_CARTAO_SUS)
-- VALUES ('11111111111', '1955-05-14', 'endereco1', 'medico-diabetes', 1, '83987000001', 'numeroCartaoSus1');
--
-- INSERT INTO cidadao (CPF, DATA_NASCIMENTO, ENDERECO, NOME, PROFISSAO, TELEFONE, REGISTRO_VACINACAO_NUMERO_CARTAO_SUS)
-- VALUES ('22222222222', '1981-05-14', 'endereco2', 'caminhoneiro-asma', 2, '83987000002', 'numeroCartaoSus2');
--
-- INSERT INTO cidadao (CPF, DATA_NASCIMENTO, ENDERECO, NOME, PROFISSAO, TELEFONE, REGISTRO_VACINACAO_NUMERO_CARTAO_SUS)
-- VALUES ('33333333333', '1951-05-14', 'endereco3', 'idoso', 3, '83987000003', 'numeroCartaoSus3');
--
-- INSERT INTO cidadao (CPF, DATA_NASCIMENTO, ENDERECO, NOME, PROFISSAO, TELEFONE, REGISTRO_VACINACAO_NUMERO_CARTAO_SUS)
-- VALUES ('44444444444', '1950-05-14', 'endereco4', 'idoso-diabetes', 1, '83987000004', 'numeroCartaoSus4');
--
-- -- Usuários
--
-- INSERT INTO usuario (EMAIL, PERMISSAO_ADMINISTRADOR, PERMISSAO_CIDADAO, PERMISSAO_FUNCIONARIO, SENHA, CADASTRO_CIDADAO_CPF, CADASTRO_FUNCIONARIO_CPF)
-- VALUES ('email1', false, true, false, 'senha1', '11111111111', null);
--
-- INSERT INTO usuario (EMAIL, PERMISSAO_ADMINISTRADOR, PERMISSAO_CIDADAO, PERMISSAO_FUNCIONARIO, SENHA, CADASTRO_CIDADAO_CPF, CADASTRO_FUNCIONARIO_CPF)
-- VALUES ('email2', false, true, false, 'senha2', '22222222222', null);
--
-- INSERT INTO usuario (EMAIL, PERMISSAO_ADMINISTRADOR, PERMISSAO_CIDADAO, PERMISSAO_FUNCIONARIO, SENHA, CADASTRO_CIDADAO_CPF, CADASTRO_FUNCIONARIO_CPF)
-- VALUES ('email3', false, true, false, 'senha3', '33333333333', null);
--
-- INSERT INTO usuario (EMAIL, PERMISSAO_ADMINISTRADOR, PERMISSAO_CIDADAO, PERMISSAO_FUNCIONARIO, SENHA, CADASTRO_CIDADAO_CPF, CADASTRO_FUNCIONARIO_CPF)
-- VALUES ('email4', false, true, false, 'senha4', '44444444444', null);
--
-- -- Comorbidades Cidadãos
--
-- INSERT INTO cidadao_comorbidades (CIDADAO_CPF, COMORBIDADES_ID)
-- VALUES ('11111111111', 1);
--
-- INSERT INTO cidadao_comorbidades (CIDADAO_CPF, COMORBIDADES_ID)
-- VALUES ('22222222222', 2);
--
-- INSERT INTO cidadao_comorbidades (CIDADAO_CPF, COMORBIDADES_ID)
-- VALUES ('22222222222', 3);
--
-- INSERT INTO cidadao_comorbidades (CIDADAO_CPF, COMORBIDADES_ID)
-- VALUES ('44444444444', 1);